hero/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from information import views
from posts import urls as postsUrl
from information import urls as mainUrls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(mainUrls, namespace='information')),
    url(r'^blog/', include(postsUrl, namespace='posts')),
]

information/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Descripcion.as_view(), name='home'),
]

posts/urls.py
from django.conf.urls import url, include
from . import views
#from information import urls as viewInformation

urlpatterns = [
    url(r'^$', views.ListView.as_view(), name='blog'),
    url(r'^nuevo/$', views.NuevoPost.as_view(), name='new'),
    url(r'^(?P<slug>[\w-]+)/$', views.DetailView.as_view(), name="detalle"),
    #url(r'^', views.viewInformation.as_view(), name='homeReturn')
]

information/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class Post(models.Model):
    STATUS_CHOICE = (
        ('draft','Draft'),
        ('piblished','Published'),
    )
    autor = models.ForeignKey(
        User,
        related_name='blog_post',
        blank=True,
        null=True,
    )
    titulo = models.CharField(max_length = 100)
    cuerpo = models.TextField()
    creado = models.DateTimeField(
        auto_now = True,
        blank = True,
        null = True
    )
    actualizado = models.DateTimeField(
        auto_now_add = True,
        blank = True,
        null = True
    )
    status = models.CharField(
        max_length = 10,
        choices = STATUS_CHOICE,
        default = 'draft',
        blank = True,
        null = True
    )
    slug = models.SlugField(
        max_length = 200,
        unique_for_date = 'creado',
        blank = True,
        null = True
    )

    class Meta:
        ordering = ('-creado', )

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('posts:detalle', args=[self.slug])

class Comentario(models.Model):
    post = models.ForeignKey(
        Post,
        related_name = 'comments',
        blank = True,
        null = True,
    )
    autor = models.CharField(
        max_length = 80,
        blank = True,
        null = True,
    )
    email = models.EmailField(
        blank = True,
        null = True,
    )
    cuerpo = models.TextField()
    fecha = models.DateTimeField(
        auto_now_add = True,
        blank = True,
        null = True,
    )
    activo = models.BooleanField(default=True)

    class Meta:
        ordering = ('-fecha',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.autor, self.post)

posts/forms.py
from django import forms
from .models import Post, Comentario


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['titulo','cuerpo']

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['autor', 'email', 'cuerpo']

information/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import View
from .marvelAPI import *
# Create your views here.
class Descripcion(View):
    def get(self, request):
        #avengers = ['thor', 'hulk','iron man']
        #n = len(avengers)
        template_name = 'descripcion.html'
        ultron = PachuMarvel()
        ultron.get_personaje('ultron')
        context = {
            'name': ultron.nombre.capitalize(),
            'descripcion': ultron.descripcion,
            'img': ultron.img,
        }
        return render(request, template_name, context)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from .models import Post, Comentario
from django.contrib.auth.models import User
from .forms import PostForm, ComentarioForm
from django.utils.text import slugify
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

class ListView(View):
    def get(self, request):
        template_name = 'blog.html'
        user = User.objects.get(username='luis')
        posts = user.blog_post.all()
        #print(user,' ', posts)
        context = {
            'entradas': posts
        }
        return render(request, template_name, context)

class DetailView(View):
    def get(self,request,slug):
        template_name = 'detalle.html'
        post = Post.objects.get(slug=slug)
        form = ComentarioForm()
        comment = post.comments.filter(activo = True)
        #print(comment)
        context = {
            'post': post,
            'comments': comment,
            'form': form,
        }
        #url = post.get_absolute_url
        #redirect(url)
        return render(request, template_name, context)

    def post(self, request, slug):
        form = ComentarioForm(request.POST)
        if form.is_valid():
            post = Post.objects.get(slug=slug)
            #print(post)
            newComment = form.save(commit=False)
            newComment.post = post
            newComment.save()
            form.save()
            messages.success(request, 'Hey! que buen comentario...')
            return redirect('posts:detalle', slug=slug)
        else:
            messages.error(request, 'Intentalo de nuevo')
            return redirect('posts:detalle', slug=slug)


class NuevoPost(View):
    @method_decorator(login_required)
    def get(self, request):
        template_name = 'nuevo.html'
        form = PostForm()
        context = {
            'form': form,
        }
        return render(request, template_name, context)

    def post(self,request):
        template_name = 'nuevo.html'
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            NuevoPost = form.save(commit = False)
            NuevoPost.slug = slugify(NuevoPost.titulo)
            NuevoPost.user = request.user
            NuevoPost.save()
            messages.success(request, 'Gran Post Guardado')
            return redirect('posts:blog')
        else:
            messages.error(request, 'Intentalo de nuevo')
            return redirect('posts:new')





        '''
        titulo = request.POST.get('titulo')
        cuerpo = request.POST.get('cuerpo')
        post = Post() #instanciar
        post.titulo = titulo
        post.cuerpo = cuerpo
        try:
            post.autor = request.user
        except:
            pass
        post.save()
        template_name = 'nuevo.html'
        context = {
            'guardado': True
        }
        return render(request, template_name, context)'''

information/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <title>
      {%block titulo%}
      poke Marvel
      {%endblock titulo%}
    </title>
  </head>
  <body>

      <nav>
        <div class="nav-wrapper">
          <a href="" class="brand-logo">Logo</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">nts</a></li>
            <li><a href="collapsible.html">Javascript</a></li>
            <li><a href="mobile.html">Poque</a></li>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li><a href="collapsible.html">Javascript</a></li>
            <li><a href="mobile.html">Mobile</a></li>
          </ul>
        </div>
      </nav>

    <section class="section">
      <article class="container">
        {%block content%}
        {%endblock content%}
      </article>
    </section>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script>
      $(".button-collapse").sideNav();
    </script>
  </body>
</html>

information/templates/descripcion.html
{% extends "base.html" %}
{% block titulo %}
{% endblock titulo %}
{% block content %}
<h1>{{name}}</h1>
<img src="{{img}}" style="width: 30%; heigth: 30%;">
<p>{{descripcion}}</p>
{% endblock content %}

posts/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <title>
      {%block titulo%}
      poke Marvel
      {%endblock titulo%}
    </title>
  </head>
  <body>

      <nav>
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">Logo</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li><a href="collapsible.html">Javascript</a></li>
            <li><a href="mobile.html">Mobile</a></li>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li><a href="collapsible.html">Javascript</a></li>
            <li><a href="mobile.html">Mobile</a></li>
          </ul>
        </div>
      </nav>
              
    <section class="section">
      <article class="container">
        {%block content%}
        {%endblock content%}
      </article>
    </section>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script>
      $(".button-collapse").sideNav();
    </script>
  </body>
</html>

posts/templates/basePosts.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <title>
      {%block titulo%}
      poke Marvel
      {%endblock titulo%}
    </title>
  </head>
  <body>

      <nav>
        <div class="nav-wrapper">
          <a href="{%url 'information:home'%}" class="brand-logo">Logo</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Com</a></li>
            <li><a href="collapsible.html">Prqueno lo toma</a></li>
            <li><a href="mobile.html">Mobile</a></li>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="sass.html">ss</a></li>
            <li><a href="badges.html">Cnents</a></li>
            <li><a href="collapsible.html">ipt</a></li>
            <li><a href="mobile.html">dw</a></li>
          </ul>
        </div>
      </nav>

    <section class="section">
      <article class="container">
        {%block content%}
        {%endblock content%}
      </article>
    </section>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script>
      $(".button-collapse").sideNav();
    </script>
  </body>
</html>

posts/templates/blog.html
{%extends 'basePosts.html'%}
{%block titulo%}
  Poke-BLog
{%endblock titulo%}
{%block content%}
  {% for entrada in entradas %}
  <!-- <a href="{#{url 'posts:detalle' entrada.id }#}"><h2>entrada.titulo</h2></a>-->
    <a href="{{entrada.get_absolute_url}}"><h2>{{entrada.titulo}}</h2></a>
    <p style="text-align: justify; padding: 3%;">
      {{entrada.cuerpo}}
    </p>
    <h4>{{entrada.fecha}}</h4>
    {% empty %}
    <h2>No hay Post</h2>
  {% endfor %}
  <a href="{%url 'posts:new'%}"class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
{%endblock content%}

posts/templates/detalle.html
{%extends 'basePosts.html'%}
{% block titulo %}
{{post.titulo}}
{% endblock titulo %}
{%block content%}
  <h1>{{post.titulo}}</h1>
  <p>
    {{post.cuerpo}}
  </p>
  <strong>{{post.creado}}</strong>
  <a href="{%url 'posts:blog' %}">Regresar</a>
  <form action="." method="post">
		{%csrf_token%}
		{{form.as_p}}
		<input type="submit" value="Comentar">
	</form>
{% for comment in comments %}
  <ul class="collection">
    <li class="collection-item avatar">
      <img src="images/yuna.jpg" alt="" class="circle">
      <span class="title">{{comment.autor}}, {{comment.fecha}}</span>
      <p style="text-align: justify;">
        {{comment.cuerpo}}
      </p>
      <a href="" class="secondary-content"><i class="material-icons">grade</i></a>
    </li>
  </ul>
  {% empty %}
    <h4>Se el primero en dejar un Comentario </h4>
{% endfor %}

{%endblock content%}

posts/templates/nuevo.html
{% extends "basePosts.html" %}
{% block content %}
{% if guardado %}
    <h1>Se guardo </h1>
    {% else %}
      <form class="" action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="name" value="Publicar">
      </form>
      <a href="{%url 'posts:blog'%}">Cancelar</a>
{% endif %}
{% endblock content %}